In [1]:
import pandas as pd
movies=pd.read_csv("F:/BootCamp/Opencv/archive/movie.csv")
ratings=pd.read_csv("F:/BootCamp/Opencv/archive/rating.csv")

In [2]:
print(movies.head())
print(ratings.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [3]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  str
 2   genres   27278 non-null  str
dtypes: int64(1), str(2)
memory usage: 639.5 KB

In [4]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  str
dtypes: float64(1), int64(2), str(1)
memory usage: 610.4 MB

print("Total Movies",len(movies))

In [5]:
print(f"Total Movies: {len(movies)}")
print(f"Total Ratings: {len(ratings)}")
print(f"Unique Users: {ratings['userId'].nunique()}")

Total Movies: 27278
Total Ratings: 20000263
Unique Users: 138493

In [6]:
data=pd.merge(ratings,movies,on='movieId')
data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [7]:
data[data['title']=='Terminator 2: Judgment Day (1991)']['rating'].describe()

count    52244.000000
mean         3.931954
std          0.903087
min          0.500000
25%          3.500000
50%          4.000000
75%          5.000000
max          5.000000
Name: rating, dtype: float64

In [8]:
data.isnull()

          userId  movieId  rating  timestamp  title  genres
0          False    False   False      False  False   False
1          False    False   False      False  False   False
2          False    False   False      False  False   False
3          False    False   False      False  False   False
4          False    False   False      False  False   False
...          ...      ...     ...        ...    ...     ...
20000258   False    False   False      False  False   False
20000259   False    False   False      False  False   False
20000260   False    False   False      False  False   False
20000261   False    False   False      False  False   False
20000262   False    False   False      False  False   False

[20000263 rows x 6 columns]

In [9]:
print(data.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
title        0
genres       0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
popular=data.groupby('title')['rating'].count().sort_values(ascending=False).head(10)

In [12]:
print(popular)

title
Pulp Fiction (1994)                          67310
Forrest Gump (1994)                          66172
Shawshank Redemption, The (1994)             63366
Silence of the Lambs, The (1991)             63299
Jurassic Park (1993)                         59715
Star Wars: Episode IV - A New Hope (1977)    54502
Braveheart (1995)                            53769
Terminator 2: Judgment Day (1991)            52244
Matrix, The (1999)                           51334
Schindler's List (1993)                      50054
Name: rating, dtype: int64

In [13]:
print(data.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
title        0
genres       0
dtype: int64

In [14]:
data.groupby('title')['rating'].count().sort_values(ascending=False).head(1)

title
Pulp Fiction (1994)    67310
Name: rating, dtype: int64

In [15]:
data['userId'].nunique()

138493

In [16]:
data['rating'].describe()

count    2.000026e+07
mean     3.525529e+00
std      1.051989e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [17]:
movies['genres']=movies['genres'].str.replace("|"," ")

In [18]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure Fantasy Horror

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['genres'])
tf

In [22]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 56725 stored elements and shape (27278, 23)>
  Coords	Values
  (0, 1)	0.41915098224772934
  (0, 2)	0.5182685890892543
  (0, 3)	0.5057418311427628
  (0, 4)	0.26417526349980835
  (0, 8)	0.47973612958726514
  (1, 1)	0.5153114036141762
  (1, 3)	0.6217676777828729
  (1, 8)	0.5897958224417
  (2, 4)	0.6025827181224164
  (2, 18)	0.7980564314759957
  (3, 4)	0.5445407956731659
  (3, 18)	0.7211861062695482
  (3, 7)	0.4282124729283388
  (4, 4)	1.0
  (5, 0)	0.5761440202585545
  (5, 5)	0.610238706312681
  (5, 20)	0.5437525073396314
  (6, 4)	0.6025827181224164
  (6, 18)	0.7980564314759957
  (7, 1)	0.6381151242011527
  (7, 3)	0.7699409641431916
  (8, 0)	1.0
  (9, 1)	0.6367442942511372
  (9, 0)	0.5607679884473361
  (9, 20)	0.5292409346142357
  :	:
  (27265, 4)	0.6025827181224164
  (27265, 18)	0.7980564314759957
  (27266, 4)	1.0
  (27267, 4)	0.786066521250593
  (27267, 7)	0.6181419126454628
  (27268, 4)	0.6025827181224164
  (27268, 18)	0.7980564314759957
  (27269, 2)	0.8909340356345918
  (27269, 4)	0.4541327384673561
  (27270, 1)	0.41915098224772934
  (27270, 2)	0.5182685890892543
  (27270, 3)	0.5057418311427628
  (27270, 4)	0.26417526349980835
  (27270, 8)	0.47973612958726514
  (27271, 4)	1.0
  (27272, 4)	0.5460379159242152
  (27272, 12)	0.8377604636011059
  (27273, 4)	1.0
  (27274, 4)	1.0
  (27275, 1)	1.0
  (27276, 11)	0.7071067811865476
  (27276, 14)	0.7071067811865476
  (27277, 1)	0.5551245384251795
  (27277, 8)	0.6353636488572378
  (27277, 12)	0.5367958462479454

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [24]:
cosine_sim

array([[1.        , 0.81339357, 0.15918745, ..., 0.41915098, 0.        ,
        0.53748789],
       [0.81339357, 1.        , 0.        , ..., 0.5153114 , 0.        ,
        0.66079683],
       [0.15918745, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.41915098, 0.5153114 , 0.        , ..., 1.        , 0.        ,
        0.55512454],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.53748789, 0.66079683, 0.        , ..., 0.55512454, 0.        ,
        1.        ]], shape=(27278, 27278))

In [31]:
print(tfidf.get_feature_names_out())

['action' 'adventure' 'animation' 'children' 'comedy' 'crime'
 'documentary' 'drama' 'fantasy' 'fi' 'film' 'genres' 'horror' 'imax'
 'listed' 'musical' 'mystery' 'noir' 'romance' 'sci' 'thriller' 'war'
 'western']

In [27]:
indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

In [29]:
indices

title
Toy Story (1995)                          0
Jumanji (1995)                            1
Grumpier Old Men (1995)                   2
Waiting to Exhale (1995)                  3
Father of the Bride Part II (1995)        4
                                      ...
Kein Bund für's Leben (2007)          27273
Feuer, Eis & Dosenbier (2002)         27274
The Pirates (2014)                    27275
Rentun Ruusu (2001)                   27276
Innocence (2014)                      27277
Length: 27278, dtype: int64

In [28]:
def recommend(movie_name, top_n=10):
    idx = indices[movie_name]
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:top_n+1]
    
    movie_indices = [i[0] for i in sim_scores]
    
    return movies['title'].iloc[movie_indices]

In [30]:
print(recommend("Toy Story (1995)"))

2209                                           Antz (1998)
3027                                    Toy Story 2 (1999)
3663        Adventures of Rocky and Bullwinkle, The (2000)
3922                      Emperor's New Groove, The (2000)
4790                                 Monsters, Inc. (2001)
10114    DuckTales: The Movie - Treasure of the Lost La...
10987                                     Wild, The (2006)
11871                               Shrek the Third (2007)
13337                       Tale of Despereaux, The (2008)
18274    Asterix and the Vikings (Astérix et les Viking...
Name: title, dtype: str